### ISSUE TITLE
> And usually, even with open source non-commercial software you want your userbase to be somewhat high for motivation, donations and so on, don't you?

### ISSUE THREAD

**Issue by kachgold** [google/oss-policies-info#13]
> And usually, even with open source non-commercial software you want your userbase to be somewhat high for motivation, donations and so on, don't you?

You wouldn't find any piece of mine willingly offered by me in a walled garden. And similarly, there are more devs keeping their apps out of there than you might expect (we just noticed that again when some imposter published a load of those as their own, "enriched" my some "monetizing modules" to make money from other people's work – luckily their account was taken down rather quickly). But yes, I assume a bigger part putting their apps in both places (and no offense to that). As pointed out earlier, some make them paid at play while fully free at F-Droid. And believe it or not, some apps are even exclusively in my repo.

And there of course you have your point: the majority of apps in my repo, when I needed to decide on a single ABI, are 32bit indeed – while 64bit variants are available attached to their releases.

_Originally posted by @IzzySoft in https://github.com/jamie-mh/AuthenticatorPro/issues/724#issuecomment-1520925076_

**Comment by coryan** [comment]
This seems unrelated.
